name: mantis_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
 # state management
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5+1
  # freezed
  freezed_annotation: ^2.0.3
  # functional programming
  dartz: ^0.10.1
  # navigation
  auto_route: ^5.0.4
  # dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  # other
  json_serializable: ^6.2.0
  json_annotation: ^4.6.0
  flutter_screenutil: ^5.6.1
  # http
  dio: ^4.0.6
  retrofit: ^3.3.1
  pretty_dio_logger: ^1.1.1
  auto_size_text: ^3.0.0
  page_transition: ^2.0.9
  percent_indicator: ^4.2.2
  av_utils:
    git: 
      url: "git@github.com:kamilksi/av_utils.git"
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # freezed
  freezed: ^2.0.3+1
  # build runners
  build_runner: ^2.1.11
  auto_route_generator: ^5.0.3
  retrofit_generator: 4.2.0
  injectable_generator: ^1.5.3

  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/icon.png